INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [ 123.675, 116.28, 103.53 ]

  DO_PAD: True
  PADDING: 10
  PADDING_MODE: constant

  DO_FLIP: True
  FLIP_PROB: 0.5

MODEL:
  META_ARCHITECTURE: "Baseline"
  FREEZE_LAYERS: ["backbone"]

  BACKBONE:
    NAME: "build_resnet_backbone"
    NORM: "BN"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: "resnet50_ibn_a.pth"

  HEADS:
    NAME: 'HRCNHead'
    NORM: "BN"
    POOL_LAYER: "avgpool"
    CLS_LAYER: 'linear'
    NECK_FEAT: "before"
    NUM_CLASSES: 13164
    IN_FEAT: 2048
    KEEP_FIRST: True
    NODE_LIST: [3, 3, 3]
    BLOCK_NUM_LIST: [ 4, 6, 3 ]
    CENTER_NUM: 4
    CENTER_POOL_TYPE: circle
    DROPOUT: true
    GATE: 0.001
    REDUCE_DIAG: False
    FINAL_CHANNEL: [ 512, 256, 512, 256, 512 ]
    FINAL_CHANNEL_NUM: [ 1, 2, 1, 4, 2 ]
    GCN_CHANNELS: [ 1024, 1024, 1024 ]
    IN_CHANNEL_LIST: [512, 1024, 2048]
    LAST_FC_LAYER: False

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.0

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPT: "SGD"
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5
  BASE_LR_FACTOR: 0.9
  BIAS_LR_FACTOR: 1.0
  WARMUP_FACTOR: 0.01
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  SCHED: "WarmupCosineAnnealingLR"

  IMS_PER_BATCH: 48
  MAX_ITER: 120
  DELAY_ITERS: 60
  WARMUP_ITERS: 20
  FREEZE_ITERS: 20

  CHECKPOINT_PERIOD: 10

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
  METRIC: cosine
  RERANK:
    ENABLED: False

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/vehicle"
